version: '3.8'

services:
###> doctrine/doctrine-bundle ###
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/symfony

  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/symfony
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:80"
    depends_on:
      - php

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: symfony_db
      # You should definitely change the password in production
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###